firmware_loader: fix build without sysctl
firmware_config_table has references to the sysctl code which
triggers a build failure when CONFIG_PROC_SYSCTL is not set:

    ld: drivers/base/firmware_loader/fallback_table.o:(.data+0x30): undefined reference to `sysctl_vals'
    ld: drivers/base/firmware_loader/fallback_table.o:(.data+0x38): undefined reference to `sysctl_vals'
    ld: drivers/base/firmware_loader/fallback_table.o:(.data+0x70): undefined reference to `sysctl_vals'
    ld: drivers/base/firmware_loader/fallback_table.o:(.data+0x78): undefined reference to `sysctl_vals'

Put the firmware_config_table struct under #ifdef CONFIG_PROC_SYSCTL.

Fixes: 6a33853c5773 ("proc/sysctl: add shared variables for range check")
Reported-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Matteo Croce <mcroce@redhat.com>