FIXUP: ANDROID: usb: gadget: configfs: Add Uevent to notify userspace
If CONFIG_USB_CONFIGFS_UEVENT is enabled, we get the following
build errors.

drivers/usb/gadget/configfs.c:1488:12: error:
	unused function 'configfs_composite_setup'

drivers/usb/gadget/configfs.c:1513:13: error:
	unused function 'configfs_composite_disconnect'

Change-Id: Ieb29ec623e28892044371cefd00c3a93468fabae
Signed-off-by: Guenter Roeck <groeck@chromium.org>