x86/numa_emulation: Fix uniform size build failure
The calculation of a uniform numa-node size attempted to perform
division with a 64-bit diviser leading to the following failure on
32-bit:

    arch/x86/mm/numa_emulation.o: In function `split_nodes_size_interleave_uniform':
    arch/x86/mm/numa_emulation.c:239: undefined reference to `__udivdi3'

Convert the implementation to do the division in terms of pages and then
shift the result back to an absolute physical address.

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Dan Williams <dan.j.williams@intel.com>
Cc: David Rientjes <rientjes@google.com>
Cc: Linus Torvalds <torvalds@linux-foundation.org>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Thomas Gleixner <tglx@linutronix.de>
Cc: Wei Yang <richard.weiyang@gmail.com>
Cc: linux-mm@kvack.org
Fixes: 93e738834fcc ("x86/numa_emulation: Introduce uniform split capability")
Link: http://lkml.kernel.org/r/153065162801.12250.4860144566061573514.stgit@dwillia2-desk3.amr.corp.intel.com
Signed-off-by: Ingo Molnar <mingo@kernel.org>