mm-security-introduce-init_on_alloc=1-and-init_on_free=1-boot-options-fix
export init_on_alloc to modules

ERROR: "init_on_alloc" [drivers/infiniband/core/ib_uverbs.ko] undefined!

Cc: Alexander Potapenko <glider@google.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>