mm-initialize-pages-on-demand-during-boot-v6-checkpatch-fixes
ERROR: code indent should use tabs where possible
#28: FILE: mm/page_alloc.c:1620:
+ ^I * the lock, return true, as the zone was grown.  The caller will retry$

WARNING: please, no space before tabs
#28: FILE: mm/page_alloc.c:1620:
+ ^I * the lock, return true, as the zone was grown.  The caller will retry$

total: 1 errors, 1 warnings, 43 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-initialize-pages-on-demand-during-boot-v6.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Pavel Tatashin <pasha.tatashin@oracle.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>