dmaengine: fsl-edma-common: Add missing header module.h
We added MODULE_LICENSE but missed adding the header, so add it

drivers/dma/fsl-edma-common.c:672:16: error:
	expected declaration specifiers or '...' before string constant
 MODULE_LICENSE("GPL v2");
                ^~~~~~~~

Fixes: 7565699b2d21 ("dmaengine: fsl-edma-common: Add missing MODULE_LICENSE")
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Vinod Koul <vkoul@kernel.org>