compat_ioctl: block: add missing include
As the 0day bot pointed out, a header inclusion is missing in
my earlier bugfixes:

block/compat_ioctl.c: In function 'compat_blkdev_ioctl':
 block/compat_ioctl.c:411:7: error: 'IOC_PR_REGISTER' undeclared (first use in this function); did you mean 'TRACE_REG_REGISTER'?

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>