gcov: fix when CONFIG_MODULES is not set
   kernel/gcov/gcc_4_7.c: In function 'gcov_info_within_module':
> > kernel/gcov/gcc_4_7.c:162:9: error: implicit declaration of function \
> > 'within_module'; did you mean 'init_module'? \
> > [-Werror=implicit-function-declaration]
     return within_module((unsigned long)info, mod);
            ^~~~~~~~~~~~~
            init_module

Link: http://lkml.kernel.org/r/20190402030956.48166-1-trong@android.com
Link: https://marc.info/?l=linux-mm&m=155384681109231&w=2
Fixes: 8c3d220cb6b5 ("gcov: clang support")
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Signed-off-by: Tri Vo <trong@android.com>
Reported-by: Randy Dunlap <rdunlap@infradead.org>
Reported-by: kbuild test robot <lkp@intel.com>
Cc: Greg Hackmann <ghackmann@android.com>
Cc: Peter Oberparleiter <oberpar@linux.ibm.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>