FROMLIST: drm/amd/powerplay: fix struct init in renoir_print_clk_levels
drivers/gpu/drm/amd/powerplay/renoir_ppt.c:186:2: error: missing braces
around initializer [-Werror=missing-braces]
  SmuMetrics_t metrics = {0};
    ^

Fixes: 8b8031703bd7 ("drm/amd/powerplay: implement sysfs for getting dpm clock")

Signed-off-by: Raul E Rangel <rrangel@chromium.org>
(am from https://patchwork.kernel.org/patch/11229577/)
(also found at https://lkml.kernel.org/r/20191105155734.1.If8740b4a5095031f2c00746fbc3224be9849d76b@changeid)

BUG=b:141567143
TEST=Made sure grunt compiles

Signed-off-by: Raul E Rangel <rrangel@chromium.org>
Change-Id: If8740b4a5095031f2c00746fbc3224be9849d76b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel-next/+/1901830
Reviewed-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit 9eb8b53fffe4117f1106e6091e729d472b3bc10c)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel-next/+/1903883
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>