mpage-add-argument-structure-for-do_mpage_readpage-checkpatch-fixes
WARNING: Prefer 'unsigned int' to bare use of 'unsigned'
#49: FILE: fs/mpage.c:139:
+	unsigned nr_pages;

WARNING: line over 80 characters
#96: FILE: fs/mpage.c:190:
+	if (buffer_mapped(map_bh) && block_in_file > args->first_logical_block &&

WARNING: Prefer 'unsigned int' to bare use of 'unsigned'
#98: FILE: fs/mpage.c:192:
+		unsigned map_offset = block_in_file - args->first_logical_block;

WARNING: line over 80 characters
#135: FILE: fs/mpage.c:296:
+				min_t(int, args->nr_pages, BIO_MAX_PAGES), args->gfp);

ERROR: code indent should use tabs where possible
#169: FILE: fs/mpage.c:321:
+^I        block_read_full_page(page, args->get_block);$

total: 1 errors, 4 warnings, 196 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mpage-add-argument-structure-for-do_mpage_readpage.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>