CHROMIUM: low_mem: Use get_nr_swap_pages()
nr_swap_pages may be undefined for some architectures/configurations.
This can result in the following build error.

In file included from mm/page_alloc.c:63:0:
include/linux/low-mem-notify.h: In function '_is_low_mem_situation':
include/linux/low-mem-notify.h:49:42: error: 'nr_swap_pages' undeclared

Use its accessor instead of accessing it directly.

Fixes: a1d40b62c138 ("CHROMIUM: low-mem: work with swap enabled")
BUG=chromium:583462
TEST=None (build)

Change-Id: Ieaf9b3b54e60949b319759cfdfc222b2b2a94610
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325402
Reviewed-by: Luigi Semenzato <semenzato@chromium.org>