CHROMIUM: ARM: rockchip: pm: Don't use C in naked function
clang is unhappy about C statements in naked functions:

  error: non-ASM statement in naked function is not supported
    rk3288_resume_c();

Invoke rk3288_resume_c() from inline assembly instead of using
a C function call.

BUG=chromium:819808
TEST=clang doesn't complain anymore
  resume still works when building with gcc

Change-Id: I53d59e0bb8c37136485860da0559ab912c8dfc32
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1634935
Commit-Ready: Douglas Anderson <dianders@chromium.org>
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>