CHROMIUM: ALSA: hda: SND_HDA_CODEC_CA0132 depends on PCI
0day reports:

sound/pci/hda/patch_ca0132.c: In function 'ca0132_free':
sound/pci/hda/patch_ca0132.c:7398:3: error: implicit declaration of function 'pci_iounmap'
    pci_iounmap(codec->bus->pci, spec->mem_base);
    ^~~~~~~~~~~
sound/pci/hda/patch_ca0132.c: In function 'patch_ca0132':
sound/pci/hda/patch_ca0132.c:7650:20: error: implicit declaration of function 'pci_iomap'
    spec->mem_base = pci_iomap(codec->bus->pci, 2, 0xC20);
                     ^~~~~~~~~

when building sh:allmodconfig.

This problem is not seen in stable releases or in the upstream kernel.
It was introduced into chromeos-4.19 with the backport of commit 6bae5ea94989
("ASoC: hdac_hda: add asoc extension for legacy HDA codec drivers"), which
auto-enables SND_SOC_HDAC_HDA and with it SND_HDA. This in turn enables
SND_HDA_CODEC_CA0132.

The problem has been addressed upstream with a series of commits modifying
PCI related code in the affected file. Those changes enable building
the file with PCI disabled. Backporting the changes would be expensive
and not serve a real purpose. Mark SND_HDA_CODEC_CA0132 to depend on PCI
instead.

Rebase note: Do not rebase.

BUG=chromium:911025
TEST=Build sh:allmodconfig

Change-Id: Ib47daf55edfb9c768f871d1306f2f4dbcfc9d33d
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1484771
Reviewed-by: Evan Green <evgreen@chromium.org>