WIP: CHROMIUM: mm/cma: Export missing symbols
allmodconfig builds fail with:

ERROR: "cma_for_each_area" [drivers/staging/android/ion/heaps/ion_cma_heap.ko] undefined!
ERROR: "cma_alloc" [drivers/staging/android/ion/heaps/ion_cma_heap.ko] undefined!
ERROR: "cma_release" [drivers/staging/android/ion/heaps/ion_cma_heap.ko] undefined!
ERROR: "cma_get_name" [drivers/staging/android/ion/heaps/ion_cma_heap.ko] undefined!

Export the missing symbols to avoid the problem. Ultimately, we'll have
to decide if we need to carry the Android ion patches.

Change-Id: I58fae53af4381ee5cc432bfddebbf8273f9b50b0
Signed-off-by: Guenter Roeck <groeck@chromium.org>