FROMLIST: drm/amd/display: fix struct init in update_bounding_box
dcn20_resource.c:2636:9: error: missing braces around initializer [-Werror=missing-braces]
  struct _vcs_dpi_voltage_scaling_st calculated_states[MAX_CLOCK_LIMIT_STATES] = {0};
         ^

Fixes: 7ed4e6352c16f ("drm/amd/display: Add DCN2 HW Sequencer and Resource")

Signed-off-by: Raul E Rangel <rrangel@chromium.org>
(am from https://patchwork.kernel.org/patch/11173715/)
(also found at https://lkml.kernel.org/r/20191003142423.v3.1.I5c52c59b731fe266252588ab2b32c0e3d4d808f1@changeid)

BUG=b:141567143
TEST=Made sure grunt compiles

Signed-off-by: Raul E Rangel <rrangel@chromium.org>
Change-Id: I5c52c59b731fe266252588ab2b32c0e3d4d808f1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel-next/+/1901829
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>