btrfs: qgroups: remove unused label
The recent revert left one unused label behind:

fs/btrfs/qgroup.c: In function 'qgroup_reserve':
fs/btrfs/qgroup.c:2432:1: error: label 'retry' defined but not used [-Werror=unused-label]

Let's remove it, too.

Fixes: b283738ab0ad ("Revert "btrfs: qgroups: Retry after commit on getting EDQUOT"")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
[ temporary fixup until the base branch gets updated again ]
Signed-off-by: David Sterba <dsterba@suse.com>